lib/storex_web/router.ex
defmodule StorexWeb.Router do
  use StorexWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug StorexWeb.Plugs.Cart
    plug StorexWeb.Plugs.ItemsCount
    plug StorexWeb.Plugs.CurrentUser
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", StorexWeb do
    pipe_through :browser # Use the default browser stack

    get "/", BookController, :index
    get "/books/:id", BookController, :show

    resources "/carts", CartController, singleton: true, only: [:show, :create, :delete]
    resources "/users", UserController, only: [:new, :create]
    resources "/sessions", SessionController, only: [:new, :create], singleton: true
  end
end

lib/storex/store/book.ex
defmodule Storex.Store.Book do
  use Ecto.Schema
  import Ecto.Changeset
  alias Storex.Store.Book

  schema "store_books" do
    field :description, :string
    field :image_url, :string
    field :price, :decimal
    field :title, :string

    timestamps()
  end

  @doc false
  def changeset(%Book{} = book, attrs) do
    book
    |> cast(attrs, [:title, :description, :price, :image_url])
    |> validate_required([:title, :description, :price, :image_url])
  end
end

lib/storex_web/controllers/book_controller.ex
defmodule StorexWeb.BookController do
  use StorexWeb, :controller
  alias Storex.Store

  def index(conn, _params) do
    render conn, "index.html", books: Store.list_books()
  end

  def show(conn, %{"id" => book_id}) do
    render conn, "show.html", book: Store.get_book(book_id)
  end
end

lib/storex_web/views/book_view.ex
defmodule StorexWeb.BookView do
  use StorexWeb, :view
  import StorexWeb.Helpers.PriceFormatter
end

lib/storex_web/templates/book/index.html.eex
<section class="book-list">
  <ul class="grid">
    <%= for book <- @books do %>
      <li class="grid-item">
        <div class="book book-small">
          <%= link to: book_path(@conn, :show, book.id) do %>
            <img class="book__image" src="<%= book.image_url %>">
            <h2 class="book__title"><%= book.title %></h2>
          <% end %>
          <span class="book__price"><%= format_price(book.price) %></span>
        </div>
      </li>
    <% end %>
  </ul>
</section>

lib/storex_web/templates/book/show.html.eex
<h1><%= @book.title %></h1>

<div class="book book-hero">
  <img class="book__image" src="<%= @book.image_url %>">

  <p class="book__description">
    <%= @book.description %>
  </p>
</div>

<div class="value-tag">
  <h2 class="value-tag__title">price</h2>
  <span class="value-tag__content"><%= format_price(@book.price) %></span>
</div>

<%= link "Add to cart", to: cart_path(@conn, :create, book_id: @book.id), method: :create, class: "button button-primary" %>