lib/storex_web/router.ex
defmodule StorexWeb.Router do
  use StorexWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug StorexWeb.Plugs.Cart
    plug StorexWeb.Plugs.ItemsCount
    plug StorexWeb.Plugs.CurrentUser
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", StorexWeb do
    pipe_through :browser # Use the default browser stack

    get "/", BookController, :index
    get "/books/:id", BookController, :show

    resources "/carts", CartController, singleton: true, only: [:show, :create, :delete]
    resources "/users", UserController, only: [:new, :create]
    resources "/sessions", SessionController, only: [:new, :create], singleton: true
  end
end

lib/storex_web/views/layout_view.ex
defmodule StorexWeb.LayoutView do
  use StorexWeb, :view

  def items_count(conn) do
    StorexWeb.Plugs.ItemsCount.get(conn)
  end
end

lib/storex_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Welcome to Storex</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <nav class="main-nav">
      <a class="main-nav__logo" href="/"></a>

      <ul class="main-nav__links">
        <%= if @current_user do %>
          <li><%= @current_user.full_name %></li>
        <% else %>
          <li><%= link "sign up", to: user_path(@conn, :new) %></li>
          <li><%= link "sign in", to: session_path(@conn, :new) %></li>
        <% end %>

        <%= if items_count(@conn) do %>
          <li>
            <%= link to: cart_path(@conn, :show) do %>
              cart <span class="badge"><%= items_count(@conn) %></span>
            <% end %>
          </li>
        <% end %>
      </ul>
    </nav>

    <main class="content">
      <%= if message=get_flash(@conn, :info) do %>
        <p class="alert alert-info" role="alert"><%= message %></p>
      <% end %>

      <%= if message=get_flash(@conn, :error) do %>
        <p class="alert alert-danger" role="alert"><%= message %></p>
      <% end %>

      <%= render @view_module, @view_template, assigns %>
    </main>

    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>